// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-members.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.7";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_members_default = defineTool({
  name: "list_members",
  title: "Lister les membres",
  description: "Retourne la liste des membres AS.CHRIS.K (nom, pr\xE9nom, identifiant, campement, t\xE9l\xE9phone, statut). Filtres optionnels sur statut et campement, recherche par nom.",
  inputSchema: {
    search: z.string().optional().describe("Recherche libre sur nom/pr\xE9nom/identifiant."),
    status: z.enum(["actif", "suspendu", "d\xE9c\xE9d\xE9"]).optional(),
    campement: z.string().optional(),
    limit: z.number().int().min(1).max(200).optional().describe("Nombre max de r\xE9sultats (d\xE9faut 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, status, campement, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("members").select("id, member_id, first_name, last_name, phone, campement, status, adhesion_paid, contribution_status, total_covered_persons, registration_date").order("last_name", { ascending: true }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (campement) q = q.ilike("campement", `%${campement}%`);
    if (search) q = q.or(`first_name.ilike.%${search}%,last_name.ilike.%${search}%,member_id.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} membre(s) trouv\xE9(s).` }],
      structuredContent: { members: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-member.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.7";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_member_default = defineTool2({
  name: "get_member",
  title: "D\xE9tail d'un membre",
  description: "Retourne le dossier complet d'un membre : identit\xE9, coordonn\xE9es, ayants droit (secondary_members), personne de tutel (guardian), statut de cotisation et adh\xE9sion.",
  inputSchema: {
    member_id: z2.string().min(1).describe("Identifiant lisible (ex: A-25-0007) ou UUID interne.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ member_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    const supabase = supabaseForUser2(ctx);
    const isUuid = /^[0-9a-f-]{36}$/i.test(member_id);
    const { data, error } = await supabase.from("members").select("*").or(isUuid ? `id.eq.${member_id}` : `member_id.eq.${member_id}`).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Membre introuvable." }], isError: true };
    return {
      content: [{ type: "text", text: `Membre ${data.member_id} \u2014 ${data.last_name} ${data.first_name}` }],
      structuredContent: { member: data }
    };
  }
});

// src/lib/mcp/tools/list-contributions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.7";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_contributions_default = defineTool3({
  name: "list_contributions",
  title: "Lister les cotisations",
  description: "Retourne les cotisations enregistr\xE9es. Filtrable par statut et par d\xE9c\xE8s (death_id) ou membre (member_id).",
  inputSchema: {
    status: z3.enum(["pay\xE9", "non_pay\xE9", "partiel", "exon\xE9r\xE9"]).optional(),
    death_id: z3.string().optional(),
    member_id: z3.string().optional(),
    limit: z3.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, death_id, member_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    const supabase = supabaseForUser3(ctx);
    let q = supabase.from("contributions").select("*").order("created_at", { ascending: false }).limit(limit ?? 100);
    if (status) q = q.eq("status", status);
    if (death_id) q = q.eq("death_id", death_id);
    if (member_id) q = q.eq("member_id", member_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} cotisation(s).` }],
      structuredContent: { contributions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-deaths.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.110.7";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_deaths_default = defineTool4({
  name: "list_deaths",
  title: "Lister les d\xE9c\xE8s",
  description: "Retourne les d\xE9c\xE8s enregistr\xE9s (principal ou secondaire) avec montant revers\xE9, retenu et statut.",
  inputSchema: {
    status: z4.enum(["en_cours", "cl\xF4tur\xE9"]).optional(),
    type: z4.enum(["principal", "secondaire"]).optional(),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    const supabase = supabaseForUser4(ctx);
    let q = supabase.from("deaths").select("*").order("date_of_death", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    if (type) q = q.eq("type", type);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} d\xE9c\xE8s enregistr\xE9(s).` }],
      structuredContent: { deaths: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/treasury-summary.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.110.7";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var treasury_summary_default = defineTool5({
  name: "treasury_summary",
  title: "Synth\xE8se tr\xE9sorerie",
  description: "Retourne le solde de la caisse, cotisations collect\xE9es, r\xE9serves retenues et cotisations en attente.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    const supabase = supabaseForUser5(ctx);
    const { data, error } = await supabase.from("treasury").select("*").limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: data ? `Solde caisse: ${data.total_balance} FCFA` : "Tr\xE9sorerie non initialis\xE9e." }],
      structuredContent: { treasury: data ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fkdyuziqjpybnoirqsci";
var mcp_default = defineMcp({
  name: "aschrisk-mcp",
  title: "AS.CHRIS.K MCP",
  version: "0.1.0",
  instructions: "Outils de gestion de l'Association des Chr\xE9tiens de Kouassikankro (AS.CHRIS.K). Permet de consulter les membres, ayants droit, personne de tutel, d\xE9c\xE8s, cotisations et tr\xE9sorerie via l'identit\xE9 de l'utilisateur connect\xE9.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_members_default, get_member_default, list_contributions_default, list_deaths_default, treasury_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
